"""empty message

Revision ID: 003426458ef7
Revises: 78f1b75ed23e
Create Date: 2022-10-06 07:04:23.897851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003426458ef7'
down_revision = '78f1b75ed23e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blocked_tokens', schema=None) as batch_op:
        batch_op.drop_constraint('blocked_tokens_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blocked_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('blocked_tokens_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
