"""empty message

Revision ID: 78f1b75ed23e
Revises: 4db48abb96ba
Create Date: 2022-09-30 07:47:17.000839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '78f1b75ed23e'
down_revision = '4db48abb96ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('token_type', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blocked_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blocked_tokens_jti'), ['jti'], unique=False)

    op.drop_table('blacklist_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_public_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('users_public_id_key', ['public_id'])

    op.create_table('blacklist_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('blacklisted_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='blacklist_tokens_pkey'),
    sa.UniqueConstraint('token', name='blacklist_tokens_token_key')
    )
    with op.batch_alter_table('blocked_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blocked_tokens_jti'))

    op.drop_table('blocked_tokens')
    # ### end Alembic commands ###
