"""empty message

Revision ID: b172852f5c57
Revises: 
Create Date: 2022-09-10 16:24:32.674428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b172852f5c57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=120), nullable=True),
    sa.Column('author_email', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['author_email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('social_platform', sa.String(length=20), nullable=False),
    sa.Column('account_url', sa.String(length=120), nullable=False),
    sa.Column('image_url', sa.String(length=120), nullable=False),
    sa.Column('reporter_email', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['reporter_email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_table('post')
    op.drop_table('user')
    # ### end Alembic commands ###
